<?php
$this->headScript()->appendFile($this->basePath . '/js/jquery.shiftcheckbox.js', 'text/javascript');
?>
<script type="text/javascript">
$(document).ready (function () {
	$('input[type=checkbox]').shiftcheckbox();
});
</script>

<h2>Edycja projektu <?php echo $this->project ?></h2>
<?php
	if ($this->project->isAllowed($this->currentUser, 'edit')):
		echo $this->form->setAction($this->url(array('controller' => 'projects', 'action' => $this->formAction)));
?>

<?php
		if ($this->project->id != null):
			$deleteForm = new Zend_Form();
			$deleteForm->addElement('submit', 'submit', array(
				'label' => 'Usuń projekt',
			));

			$deleteForm->addElement('hidden', 'project_id', array(
				'value' => $this->project->id
			));
			echo '<hr />';
			echo $deleteForm->setAction($this->url(array('controller' => 'projects', 'action' => 'delete', 'id' => $this->project->id)));
		endif;

	endif;
?>