<h2>Lista grup</h2>

<p><a href="<?php echo $this->url(array('action' => 'new')) ?>" class="button withtext add">Dodaj nową</a></p>

<?php if ($this->groups): ?>
<ul class="list">
<?php foreach ($this->groups as $group): ?>
<?php if ($group->isAllowed($this->currentUser, 'show')): ?>
<li>
	<a href="<?php echo $group->getUrl() ?>"><?php echo $group ?></a>
</li>
<?php endif ?>
<?php endforeach; ?>
</ul>
<?php endif ?>
