<h2>Pracownicy</h2>
<?php if ($this->users): ?>
<ul>
<?php foreach ($this->users as $user): ?>
<?php if ($user->isAllowed($this->currentUser, 'show')): ?>
<li><a href="<?php echo $user->getUrl() ?>"><?php echo $user ?></a></li>
<?php endif ?>
<?php endforeach; ?>
</ul>
<?php endif ?>

<!--<?php if ($this->currentUser->role == Centixx_Acl::ROLE_HR): ?>
<a href="<?php echo $this->url(array('action' => 'add')); ?>">Dodaj nowego</a>
<?php endif ?>-->