<h2>Hej adminie!</h2>
<h3>Logi systemowe</h3>
<p>Małe, niedopracowane i bez żadnych limitów i filtrowania</p>
<div class="logViewer">
<pre><?php foreach ($this->logs as $logLine){ echo '<div>' . $logLine . PHP_EOL . '</div>'; } ?></pre>
</div>
<h3>Kopia zapasowa bazy danych</h3>
<form method="POST" action="<?php echo $this->url(array('controller' => 'admin', 'action' => 'make-backup')) ?>">
	<input type="submit" value="Utwórz kopię" />
</form>
