<h2>Panel administracyjny</h2>
<h3>Logi systemowe</h3>
<div class="logViewer">
	<pre><?php foreach ($this->logs as $logLine){ echo '<div>' . $logLine . PHP_EOL . '</div>'; } ?></pre>
</div>
<form method="POST" action="<?php echo $this->url(array('controller' => 'admin', 'action' => 'clear-logs')) ?>">
	<input type="submit" id="clearLogs" value="Wyczyść logi" />
</form>

<h3>Kopia zapasowa bazy danych</h3>
<form method="POST" action="<?php echo $this->url(array('controller' => 'admin', 'action' => 'make-backup')) ?>">
	<input type="submit" id="dbBackup" value="Utwórz kopię" />
</form>
