<h2>Pracownicy</h2>

<?php
if (count($this->permissions) > 0) {
	echo '<p>Posiadasz ';
	foreach ($this->permissions as $p) {
		echo $p->getDescription();
	}
	echo '</p>';
}
?>
<p style="text-align: right;">
	<a href="<?php echo $this->url(array('controller' => 'users', 'action' => 'add')) ?>" class="button withtext add">Dodaj nowego użytkownika</a>
</p>
<?php if ($this->users): ?>
<table class="staffing">
<thead>
<tr>
	<td>Id</td>
	<td>Nazwisko</td>
	<td>Imie</td>
	<td>Email</td>
	<td>Stanowisko</td>
	<td>Grupa</td>
	<td>Stawka</td>
	<td>Nr konta</td>
	<td style="width: 40px;"></td>
</tr>
</thead>
<tbody>
<?php foreach ($this->users as $user): ?>
<?php if ($user->isAllowed($this->currentUser, 'show')): ?>
<tr>
	<td><?php echo ++$i ?>.</td>
	<td><?php echo $user->getSurname() ?></td>
	<td><?php echo $user->getName() ?></td>
	<td><?php echo $user->getEmail()?></td>
	<td><?php echo join(', ', $user->getRoles()) ?></td>
	<td>
		<?php if ($user->getGroup() == null): ?>
			---
		<?php else: ?>
			<?php echo $user->getGroup() ?>
		<?php endif?>
	</td>
	<td>
		<?php if ($user->hasRole(Centixx_Acl::ROLE_CEO) && !$this->currentUser->hasPermission(Centixx_Model_Permission::TYPE_ADD_CEO)):?>
			---
		<?php else: ?>
		<?php echo $user->getHourRate() . " zł"?>
		<?php endif?>
	</td>
	<td>
		<?php if ($user->hasRole(Centixx_Acl::ROLE_CEO) && !$this->currentUser->hasPermission(Centixx_Model_Permission::TYPE_ADD_CEO)):?>
			---
		<?php else: ?>
			<?php echo $user->getAccount()?>
		<?php endif?>

	</td>
	<td>
		<?php if ($user->hasRole(Centixx_Acl::ROLE_CEO) && !$this->currentUser->hasPermission(Centixx_Model_Permission::TYPE_ADD_CEO)):?>
				---
		<?php else: ?>
			<a href="<?php echo $user->getUrl('edit')?>" class="button edit" title="Edycja">Edycja</a>
			<a href="<?php echo $user->getUrl('delete')?>" class="button delete" title="Usuń">Usuń</a>
		<?php endif?>

	</td>
</tr>
<?php endif ?>
<?php endforeach; ?>
</tbody>
</table>
<?php endif ?>