<h2>Grupa <?php echo $this->group ?></h2>
<p>Kierownik: <?php echo $this->group->getManager() ?></p>
<?php if ($this->group->users): ?>
<ul class="group-users">
<?php foreach ($this->group->users as $user): ?>
	<li class="<?php echo ($this->group->isManager($user)) ? 'manager' : 'user' ?>">
		<a href="<?php echo $user->profileHref() ?>"><?php echo $user ?></a>
	</li>
<?php endforeach ?>
</ul>
<?php endif ?>

<?php if ($this->group->isAllowed($this->currentUser, 'edit')): ?>
	<a href="<?php echo $this->url(array('controller' => 'groups', 'action' => 'edit', 'id' => $this->group->id)) ?>">Edytuj</a>
<?php endif ?>