<h2>Grupa <?php echo $this->group ?></h2>

<?php if ($this->group->isAllowed($this->currentUser, 'edit')): ?>
	<a href="<?php echo $this->group->getUrl('edit') ?>">Edytuj</a>
<?php endif ?>

<p>Kierownik: <?php echo $this->group->manager ?></p>
<p>Projekt: <?php echo $this->group->project ?></p>
<?php if ($this->group->users): ?>
<ul class="group-users">
<?php foreach ($this->group->users as $user): ?>
	<li class="<?php echo ($this->group->isManager($user)) ? 'manager' : 'user' ?>">
		<a href="<?php echo $user->getUrl() ?>"><?php echo $user ?></a>
	</li>
<?php endforeach ?>
</ul>
<?php endif ?>