<h2>Transakcje</h2>

<?php if($this->transactions): ?>
<?php $index = 1 ?>
<table class="staffing">
<thead>
<tr>
	<td>Id</td>
	<td>Pracownik</td>
	<td>Nr konta</td>
	<td>Kwota</td>
	<td>Tytuł</td>
	<td>Data</td>
	<td></td>
</tr>
</thead>
<tbody>
<?php foreach ($this->transactions as $transaction): ?>
<tr>
	<td id = "id"><?php echo $transaction->getId()?></td>
	<td id = "user<?php echo $transaction->getId()?>"><?php echo $transaction->getUser()?> </td>
	<td id = "account<?php echo $transaction->getId()?>"><?php echo $transaction->getAccount() ?></td>
	<td id = "value<?php echo $transaction->getId()?>"><?php echo $transaction->getValue()?></td>
	<td id = "title<?php echo $transaction->getId()?>"><?php echo $transaction->getTitle() ?></td>
	<td id = "date<?php echo $transaction->getId()?>"><?php echo $transaction->getDate() ?></td>
	<td><img alt="Generuj przelew" src="../public/img/edit.png" onclick="popup(<?php echo $transaction->getId()?>)"/></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php endif ?>

<a href="<?php echo $this->url(array('controller' => 'accounting', 'action' => 'generate')) ?>">GENERUJ PRZELEWY</a>

<script type="text/javascript">

function popup(index){
	var controller = "accounting";
	var account = document.getElementById("account" + index).firstChild.nodeValue;
	var value = document.getElementById("value" + index).firstChild.nodeValue;
	window.open(controller + "/print/id/" + index);
}

</script>
