<h2>Transakcje</h2>

<p style="text-align: right;"><a href="<?php echo $this->url(array('controller' => 'accounting', 'action' => 'generate')) ?>" class="button withtext accept">Generuj przelewy</a></p>
<?php if($this->transactions): ?>
<?php $index = 1 ?>
<table class="staffing">
<thead>
<tr>
	<td>Id</td>
	<td>Pracownik</td>
	<td>Nr konta</td>
	<td>Kwota</td>
	<td>Tytuł</td>
	<td>Data</td>
	<td></td>
</tr>
</thead>
<tbody>
<?php foreach ($this->transactions as $transaction): ?>
<tr id="id-<?php echo $transaction->getId()?>">
	<td><?php echo $transaction->getId()?></td>
	<td><?php echo $transaction->getUser() ?></td>
	<td><?php echo $transaction->getAccount()?></td>
	<td><?php echo $transaction->getValue()?> PLN</td>
	<td><?php echo $transaction->getTitle() ?></td>
	<td><?php echo $transaction->getDate() ?></td>
	<td><a href="<?php echo $this->url(array('controller' => 'accounting', 'action' => 'print', 'id' => $transaction->id)) ?>" class="button withtext printer">Generuj blankiet</a></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php endif ?>


<script type="text/javascript">
$(function() {
	$('a.button.printer').click(function() {
		window.open(this.href);
		return false;	
	});
})

</script>
