<style type="text/css">
	.main { position: relative; width: 820px; height: 488px; font-family: Courier New; font-size: 12pt; font-weight: bold; letter-spacing:12.5px; }
	.blankiet1 { z-index:0; }
	.blankiet2 { z-index:1; }
	.odbiorca1 { position: absolute; top: 25px; left: 111px; }
	.odbiorca2 { position: absolute; top: 62px; left: 111px; }
	.konto1 { position: absolute; top: 100px; left: 158px; }
	.konto2 { position: absolute; top: 139px; left: 112px; }
	.kwota1 { position: absolute; top: 139px; left: 453px; }
	.kwota2 { position: absolute; top: 177px; left: 112px; }
	.zlec1 { position: absolute; top: 217px; left: 111px; }
	.zlec2 { position: absolute; top: 254px; left: 111px; }
	.tytul1 { position: absolute; top: 294px; left: 111px; }
	.tytul2 { position: absolute; top: 331px; left: 111px; }
</style>


<div class="main">
<div class="blankiet1"><img src="blankiet.jpg" border="0" style="width: 820px; height: 488px;"></div>
<div class="blankiet2">
	<div class="odbiorca1"><?php echo $this->odbiorca1; ?></div>
	<div class="odbiorca2"><?php echo $this->odbiorca2; ?></div>
	<div class="konto1"><?php echo $this->konto1; ?></div>
	<div class="konto2"><?php echo $this->konto2; ?></div>
	<div class="kwota1"><?php echo $this->kwota; ?></div>
	<div class="kwota2">blablabla<?php echo $this->kwotaSlownie; ?></div>
	<div class="zlec1"><?php echo $this->zlec1; ?></div>
	<div class="zlec2"><?php echo $this->zlec2; ?></div>
	<div class="tytul1"><?php echo $this->tyt1; ?></div>
	<div class="tytul2"><?php echo $this->tyt2; ?></div>
</div>

<div class="main">
<div class="blankiet1"><img src="blankiet.jpg" border="0" style="width: 820px; height: 488px;"></div>
<div class="blankiet2">
	<div class="odbiorca1"><?php echo $this->odbiorca1; ?></div>
	<div class="odbiorca2"><?php echo $this->odbiorca2; ?></div>
	<div class="konto1"><?php echo $this->konto1; ?></div>
	<div class="konto2"><?php echo $this->konto2; ?></div>
	<div class="kwota1"><?php echo $this->kwota; ?></div>
	<div class="kwota2">blablabla<?php echo $this->kwotaSlownie; ?></div>
	<div class="zlec1"><?php echo $this->zlec1; ?></div>
	<div class="zlec2"><?php echo $this->zlec2; ?></div>
	<div class="tytul1"><?php echo $this->tyt1; ?></div>
	<div class="tytul2"><?php echo $this->tyt2; ?></div>
</div>
</div>