<h2>Raporty</h2>

<!-- tabs -->

<div id="demo" class="demolayout">

	<ul id="demo-nav" class="demolayout">
	<?php if($this->deny == '0') {
		echo '<li><a href="#tab1">Zbiorczy</a></li>';
	} ?>
		<li><a href="#tab3">Projekty</a></li>
	</ul>
    
	<div class="tabs-container">
		<?php if($this->deny == '0') {
		echo '
		<div class="tab" id="tab1">
		    <h2>TRWAJĄCE</h2>
		    <p>
		    	<div id="container-zb-cash" style="width: 800px; height: 400px; margin: 0 auto"></div>
		    	<div id="container-zb-time" style="width: 800px; height: 400px; margin: 0 auto"></div>
			</p>
		    <h2>ZAKOŃCZONE</h2>
		    <p>
		    	<div id="container-zb-cash_end" style="width: 800px; height: 400px; margin: 0 auto"></div>
		    	<div id="container-zb-time_end" style="width: 800px; height: 400px; margin: 0 auto"></div>
			</p>
		</div>	
		';
		} ?>
		
		<div class="tab" id="tab3">
	
			<!-- nested -->
			<div id="demo-nested" class="demolayout">
			
				<ul id="demo-nested-nav" class="demolayout">
					<?php 
						foreach($this->chartProjectsCashData as $key => $value) {
							echo "<li><a href=\"#\">$key</a></li>";
						}
					?>
				</ul>
			
				<div class="tabs-container">
					<?php 
						$k=0;
						foreach($this->chartProjectsCashData as $key => $value) {
							$k++;
							echo '<div class="tab-nested">';
							echo "<h2>$key</h2>";
							echo "<div id=\"container-cash-proj$k\" style=\"width: 800px; height: 400px; margin: 0 auto\"></div>";
							echo "<div id=\"container-time-proj$k\" style=\"width: 800px; height: 400px; margin: 0 auto\"></div>";
							echo '</div>';
						}
					?>
				</div>
			</div>
			
			<script type="text/javascript">
				var tabber2 = new Yetii({
					id: 'demo-nested',
					tabclass: 'tab-nested'
				});
			</script>
			<!-- nested -->
		
		</div>	
	
	</div>
</div>

<script type="text/javascript">
	var tabber1 = new Yetii({
		id: 'demo',
		persist: true
	});
</script>

<!-- tabs -->

<script type="text/javascript">
	if($('#container-zb-time').size()) {
		var chart;
		$(document).ready(function() {
			chart = new Highcharts.Chart({
				chart: {
					renderTo: 'container-zb-time'
				},
				title: {
					text: 'Czasochłonność projektów'
				},
				plotArea: {
					shadow: null,
					borderWidth: null,
					backgroundColor: null
				},
				tooltip: {
					formatter: function() {
						return '<b>'+ this.point.name +'</b>: '+ this.y +' godzin';
					}
				},
				plotOptions: {
					pie: {
						allowPointSelect: true,
						cursor: 'pointer',
						dataLabels: {
							enabled: true,
							color: '#000000',
							connectorColor: '#000000',
							formatter: function() {
								return '<b>'+ this.point.name +'</b>: '+ this.y +' godzin';
							}
						}
					}
				},
			    series: [{
					type: 'pie',
					name: 'Browser share',
					data: [
						<?php $count = count($this->chartOverallTime);
						$i = 0;
						foreach ($this->chartOverallTime as $key => $value) {
							$i++;
							echo '[\''.$key.'\','.$value.']';
							if($count != $i) echo ',';
						} ?>
					]
				}]
			});
		});
	}
</script>

<script type="text/javascript">
if($('#container-zb-cash').size()) {
	var chart;
	$(document).ready(function() {
		chart = new Highcharts.Chart({
			chart: {
				renderTo: 'container-zb-cash'
			},
			title: {
				text: 'Koszt projektów'
			},
			plotArea: {
				shadow: null,
				borderWidth: null,
				backgroundColor: null
			},
			tooltip: {
				formatter: function() {
					return '<b>'+ this.point.name +'</b>: '+ this.y +' zł';
				}
			},
			plotOptions: {
				pie: {
					allowPointSelect: true,
					cursor: 'pointer',
					dataLabels: {
						enabled: true,
						color: '#000000',
						connectorColor: '#000000',
						formatter: function() {
							return '<b>'+ this.point.name +'</b>: '+ this.y +' zł';
						}
					}
				}
			},
		    series: [{
				type: 'pie',
				name: 'Browser share',
				data: [
					<?php $count = count($this->chartOverallCash);
					$i = 0;
					foreach ($this->chartOverallCash as $key => $value) {
						$i++;
						echo '[\''.$key.'\','.$value.']';
						if($count != $i) echo ',';
					} ?>
				]
			}]
		});
	});
}
</script>

<script type="text/javascript">
if($('#container-zb-time_end').size()) {
	var chart;
	$(document).ready(function() {
		chart = new Highcharts.Chart({
			chart: {
				renderTo: 'container-zb-time_end'
			},
			title: {
				text: 'Czasochłonność projektów'
			},
			plotArea: {
				shadow: null,
				borderWidth: null,
				backgroundColor: null
			},
			tooltip: {
				formatter: function() {
					return '<b>'+ this.point.name +'</b>: '+ this.y +' godzin';
				}
			},
			plotOptions: {
				pie: {
					allowPointSelect: true,
					cursor: 'pointer',
					dataLabels: {
						enabled: true,
						color: '#000000',
						connectorColor: '#000000',
						formatter: function() {
							return '<b>'+ this.point.name +'</b>: '+ this.y +' godzin';
						}
					}
				}
			},
		    series: [{
				type: 'pie',
				name: 'Browser share',
				data: [
					<?php $count = count($this->chartOverallTime);
					$i = 0;
					foreach ($this->chartOverallTime_end as $key => $value) {
						$i++;
						echo '[\''.$key.'\','.$value.']';
						if($count != $i) echo ',';
					} ?>
				]
			}]
		});
	});
}
</script>
<div id="container"></div>
<script type="text/javascript">
if($('#container-zb-cash_end').size()) {
	var chart;
	$(document).ready(function() {
		chart = new Highcharts.Chart({
			chart: {
				renderTo: 'container-zb-cash_end'
			},
			title: {
				text: 'Koszt projektów'
			},
			plotArea: {
				shadow: null,
				borderWidth: null,
				backgroundColor: null
			},
			tooltip: {
				formatter: function() {
					return '<b>'+ this.point.name +'</b>: '+ this.y +' zł';
				}
			},
			plotOptions: {
				pie: {
					allowPointSelect: true,
					cursor: 'pointer',
					dataLabels: {
						enabled: true,
						color: '#000000',
						connectorColor: '#000000',
						formatter: function() {
							return '<b>'+ this.point.name +'</b>: '+ this.y +' zł';
						}
					}
				}
			},
		    series: [{
				type: 'pie',
				name: 'Browser share',
				data: [
					<?php $count = count($this->chartOverallCash);
					$i = 0;
					foreach ($this->chartOverallCash_end as $key => $value) {
						$i++;
						echo '[\''.$key.'\','.$value.']';
						if($count != $i) echo ',';
					} ?>
				]
			}]
		});
	});
}
</script>
<?php
	$i=0;
	foreach($this->chartProjectsCashData as $key => $value) {
		$i++;
?>
		<script type="text/javascript">
			var chart;
			$(document).ready(function() {
				chart = new Highcharts.Chart({
					chart: {
						renderTo: 'container-cash-proj<?php echo $i.'\''; ?>
					},
					title: {
						text: 'Zestawienie kosztu projektu'
					},
					plotArea: {
						shadow: null,
						borderWidth: null,
						backgroundColor: null
					},
					tooltip: {
						formatter: function() {
							return '<b>'+ this.point.name +'</b>: '+ this.y +' zł';
						}
					},
					plotOptions: {
						pie: {
							allowPointSelect: true,
							cursor: 'pointer',
							dataLabels: {
								enabled: true,
								color: '#000000',
								connectorColor: '#000000',
								formatter: function() {
									return '<b>'+ this.point.name +'</b>: '+ this.y +' zł';
								}
							}
						}
					},
				    series: [{
						type: 'pie',
						name: 'Browser share',
						data: [
							<?php 
								$users = split(";",$value);
								$count_u = count($users)-1;
								for ($j=0; $j<$count_u; $j++) {
									$data = split(",",$users[$j]);
									echo '[\''.$data[0].'\','.(int)$data[1].']';
									if($j != $count_u-1) echo ',';
								} ?>
						]
					}]
				});
			});
		</script>
<?php
	} 
?>

<?php
	$i=0;
	foreach($this->chartProjectsTimeData as $key => $value) {
		$i++;
?>
		<script type="text/javascript">
			var chart;
			$(document).ready(function() {
				chart = new Highcharts.Chart({
					chart: {
						renderTo: 'container-time-proj<?php echo $i.'\''; ?>
					},
					title: {
						text: 'Zestawienie czasowe projektu'
					},
					plotArea: {
						shadow: null,
						borderWidth: null,
						backgroundColor: null
					},
					tooltip: {
						formatter: function() {
							return '<b>'+ this.point.name +'</b>: '+ this.y +' godzin';
						}
					},
					plotOptions: {
						pie: {
							allowPointSelect: true,
							cursor: 'pointer',
							dataLabels: {
								enabled: true,
								color: '#000000',
								connectorColor: '#000000',
								formatter: function() {
									return '<b>'+ this.point.name +'</b>: '+ this.y +' godzin';
								}
							}
						}
					},
				    series: [{
						type: 'pie',
						name: 'Browser share',
						data: [
							<?php 
								$users = split(";",$value);
								$count_u = count($users)-1;
								for ($j=0; $j<$count_u; $j++) {
									$data = split(",",$users[$j]);
									echo '[\''.$data[0].'\','.(int)$data[1].']';
									if($j != $count_u-1) echo ',';
								} ?>
						]
					}]
				});
			});
		</script>
<?php
	}
?>